apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: noxmg55q8-python 
  janus-idp.io/tekton: noxmg55q8-python
  backstage.io/kubernetes-id: noxmg55q8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: noxmg55q8-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml